create table if not exists public.moderation_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  status text not null check (status in ('allowed', 'blocked', 'review')),
  kind text not null check (kind in ('text', 'image', 'video')),
  purpose text not null,
  created_at timestamptz not null default now()
);

alter table public.moderation_events enable row level security;

revoke all on public.moderation_events from anon, authenticated;
